import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";
import { SidebarWrapper } from "./components";
import { Plus_Jakarta_Sans } from "next/font/google";

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "DAMAR | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jakartaSans.className}>
        <Providers>
          <Toaster position="top-center" />
          <SidebarWrapper />
          {children}
        </Providers>
      </body>
    </html>
  );
}
